package com.ccsna.ccsna;
// Generated Feb 17, 2016 8:27:38 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * County generated by hbm2java
 */
public class County  implements java.io.Serializable {


     private Integer idCounty;
     private String countyName;
     private Set agencies = new HashSet(0);

    public County() {
    }

	
    public County(String countyName) {
        this.countyName = countyName;
    }
    public County(String countyName, Set agencies) {
       this.countyName = countyName;
       this.agencies = agencies;
    }
   
    public Integer getIdCounty() {
        return this.idCounty;
    }
    
    public void setIdCounty(Integer idCounty) {
        this.idCounty = idCounty;
    }
    public String getCountyName() {
        return this.countyName;
    }
    
    public void setCountyName(String countyName) {
        this.countyName = countyName;
    }
    public Set getAgencies() {
        return this.agencies;
    }
    
    public void setAgencies(Set agencies) {
        this.agencies = agencies;
    }




}


